# Startup Applications
# Add your exec-once entries here

exec-once = waybar
exec-once = ~/.config/hypr/scripts/init_wallpaper.sh
exec-once = swaync
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = ~/.config/hypr/scripts/first_use_wizard.sh
